# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc2c08f71ebec034b8ebfd62ba295a7c434d49bdab4f0eb70ea787e1f30ce7c426e8365d7c69f3ad8ce090f2f22df286a6dd1d3fe7d960e307ef54131bf6130

test:
  secret_key_base: b7b6b8abfef46bcb63695da64cb64ef9eab0b5ec8e9ccf32bd0b3a54b442b1be337e5fcd96f1f49bf32581f1d953dd352084a3ee44225e2109b989871cfb3185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
